# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Release

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write # Publish a GitHub release
  id-token: write # Use of OIDC for npm provenance
  issues: write # Comment on released issues
  pull-requests: write # Comment on released pull requests

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - uses: googleapis/release-please-action@v4
      with:
        token:  ${{ secrets.GITHUB_TOKEN }}
        release-type: simple
